import type { ProgressData } from "./types";

export const DEFAULT_DATA: ProgressData = {
  settings: {
    nameFirst: "Falah Fauzan",
    nameSecond: "Risyqaa Syafitri",
    weddingDate: "2026-08-18",
    ceremonyTime: "08:00",
    venue: "Mempawah Convention Center",
    venueMapUrl: "",
    totalBudget: 150000000,
  },
  tasks: [
    { id: "t01", text: "Konfirmasi tanggal 18 Agustus ke Mempawah Convention Center (harga, kapasitas, fasilitas)", pic: "Kedua mempelai", date: "2026-07-14", done: false },
    { id: "t02", text: "Mulai administrasi nikah di KUA/kelurahan domisili", pic: "Risyqaa", date: "2026-07-15", done: false },
    { id: "t03", text: "Urus surat pindah nikah dari KUA Pare, Kediri", pic: "Falah", date: "2026-07-15", done: false },
    { id: "t04", text: "Survei & DP catering untuk 700 tamu", pic: "", date: "2026-07-16", done: false },
    { id: "t05", text: "Survei & DP dekorasi (konsep semi modern)", pic: "", date: "2026-07-16", done: false },
    { id: "t06", text: "Booking fotografer & videografer", pic: "", date: "2026-07-17", done: false },
    { id: "t07", text: "Booking MUA & busana pengantin", pic: "", date: "2026-07-17", done: false },
    { id: "t08", text: "Booking sound system, MC, hiburan", pic: "", date: "2026-07-18", done: false },
    { id: "t09", text: "Finalisasi rundown acara & konsep visual", pic: "", date: "2026-07-20", done: false },
    { id: "t10", text: "Desain undangan digital (WA/e-invitation)", pic: "", date: "2026-07-21", done: false },
    { id: "t11", text: "Cetak undangan fisik terbatas (keluarga inti/tokoh adat)", pic: "", date: "2026-07-23", done: false },
    { id: "t12", text: "Finalisasi daftar 700 tamu", pic: "", date: "2026-07-24", done: false },
    { id: "t13", text: "Mulai sebar undangan", pic: "", date: "2026-07-25", done: false },
    { id: "t14", text: "Fitting awal busana pengantin", pic: "", date: "2026-07-26", done: false },
    { id: "t15", text: "DP mahar & seserahan", pic: "", date: "2026-07-27", done: false },
    { id: "t16", text: "Rapat teknis dengan seluruh vendor (rundown, denah, jam kerja)", pic: "", date: "2026-07-29", done: false },
    { id: "t17", text: "Test food bersama catering", pic: "", date: "2026-07-30", done: false },
    { id: "t18", text: "Cek mockup dekorasi", pic: "", date: "2026-07-31", done: false },
    { id: "t19", text: "Selesaikan seluruh dokumen administrasi nikah", pic: "", date: "2026-08-03", done: false },
    { id: "t20", text: "Pantau RSVP & susulan undangan", pic: "", date: "2026-08-03", done: false },
    { id: "t21", text: "Booking penginapan untuk rombongan keluarga Pare, Kediri", pic: "", date: "2026-08-04", done: false },
    { id: "t22", text: "Atur jemputan dari Bandara Supadio ke Mempawah", pic: "", date: "2026-08-05", done: false },
    { id: "t23", text: "Konfirmasi jadwal kedatangan seluruh rombongan keluarga", pic: "", date: "2026-08-06", done: false },
    { id: "t24", text: "Fitting final busana pengantin", pic: "", date: "2026-08-07", done: false },
    { id: "t25", text: "Briefing tim hari-H (among tamu, keluarga bertugas)", pic: "", date: "2026-08-10", done: false },
    { id: "t26", text: "Konfirmasi jumlah tamu final ke catering", pic: "", date: "2026-08-13", done: false },
    { id: "t27", text: "H-3: Konfirmasi ulang seluruh vendor", pic: "", date: "2026-08-15", done: false },
    { id: "t28", text: "Sambut & antar rombongan keluarga ke penginapan", pic: "", date: "2026-08-16", done: false },
    { id: "t29", text: "H-1: Gladi & setup venue, cek sound & listrik", pic: "", date: "2026-08-17", done: false },
    { id: "t30", text: "H-1: Terima & simpan mahar/seserahan dengan aman", pic: "", date: "2026-08-17", done: false },
    { id: "t31", text: "Hari-H: Delegasikan koordinasi ke WO/koordinator keluarga", pic: "", date: "2026-08-18", done: false },
    { id: "t32", text: "Hari-H: Nikmati acara!", pic: "", date: "2026-08-18", done: false },
    { id: "t33", text: "Konfirmasi ketersediaan genset/backup listrik ke MCC", pic: "", date: "2026-07-14", done: false },
    { id: "t34", text: "Ikuti Bimbingan Perkawinan (bimwin) & urus sertifikatnya", pic: "Kedua mempelai", date: "2026-07-15", done: false },
    { id: "t35", text: "Suntik TT & surat keterangan sehat dari puskesmas (Risyqaa)", pic: "Risyqaa", date: "2026-07-15", done: false },
    { id: "t36", text: "Konfirmasi penghulu, 2 saksi & wali nikah untuk akad di venue", pic: "", date: "2026-07-16", done: false },
    { id: "t37", text: "Pesan cincin kawin", pic: "", date: "2026-07-18", done: false },
    { id: "t38", text: "Mulai perawatan pengantin (facial/spa/luluran)", pic: "Risyqaa", date: "2026-07-19", done: false },
    { id: "t39", text: "Pesan kue pengantin", pic: "", date: "2026-07-22", done: false },
    { id: "t40", text: "Pesan souvenir tamu (± 700 pcs)", pic: "", date: "2026-07-22", done: false },
    { id: "t41", text: "Siapkan dekorasi & wadah seserahan/hantaran", pic: "", date: "2026-07-23", done: false },
    { id: "t42", text: "Koordinasi busana keluarga inti & seragam panitia/among tamu", pic: "", date: "2026-07-26", done: false },
    { id: "t43", text: "Atur manajemen parkir & petugas parkir", pic: "", date: "2026-07-29", done: false },
    { id: "t44", text: "Booking qori/qoriah & pembaca doa untuk akad", pic: "", date: "2026-07-31", done: false },
    { id: "t45", text: "Atur keamanan/security & petugas P3K standby", pic: "", date: "2026-08-01", done: false },
    { id: "t46", text: "Siapkan tim livestream akad/resepsi (opsional)", pic: "", date: "2026-08-03", done: false },
    { id: "t47", text: "Atur konsumsi & mobilitas keluarga Kediri selama menginap", pic: "", date: "2026-08-05", done: false },
    { id: "t48", text: "Rencanakan bulan madu (opsional)", pic: "", date: "2026-08-07", done: false },
    { id: "t49", text: "Tunjuk & briefing petugas: penerima tamu, buku tamu, penjaga kotak angpau, pagar ayu/bagus", pic: "", date: "2026-08-10", done: false },
    { id: "t50", text: "Siapkan amplop uang tip untuk kru vendor di hari-H", pic: "", date: "2026-08-15", done: false },
    { id: "t51", text: "Rencanakan syukuran/tasyakuran setelah acara", pic: "", date: "2026-08-18", done: false },
  ],
  rundown: [
    { id: "r1", time: "06:00", activity: "Persiapan & make-up pengantin", note: "MUA tiba di lokasi", pic: "MUA" },
    { id: "r2", time: "07:30", activity: "Tim vendor final check", note: "Sound, dekorasi, catering siap", pic: "WO" },
    { id: "r3", time: "08:00", activity: "Akad nikah / pemberkatan", note: "Penghulu & saksi hadir", pic: "Keluarga inti" },
    { id: "r4", time: "09:00", activity: "Sesi foto keluarga", note: "Setelah akad, sebelum tamu masuk", pic: "Fotografer" },
    { id: "r5", time: "10:00", activity: "Tamu mulai berdatangan", note: "Among tamu bersiap di pintu masuk", pic: "Among tamu" },
    { id: "r6", time: "10:30", activity: "Pembukaan resepsi & kirab pengantin", note: "MC membuka acara", pic: "MC" },
    { id: "r7", time: "11:00", activity: "Sambutan keluarga & doa", note: "", pic: "Perwakilan keluarga" },
    { id: "r8", time: "11:30", activity: "Ramah tamah & hiburan", note: "Sesi foto bersama tamu di pelaminan", pic: "Hiburan" },
    { id: "r9", time: "14:00", activity: "Penutupan & sesi foto vendor", note: "", pic: "WO" },
    { id: "r10", time: "15:00", activity: "Bongkar dekorasi & serah terima venue", note: "", pic: "WO + Dekorasi" },
  ],
  arrivals: [
    { id: "a1", group: "Keluarga Falah (Pare, Kediri)", from: "Kediri", date: "2026-08-16", time: "", transport: "Pesawat via Bandara Supadio, Pontianak", count: "", note: "Datang H-2. Perlu penjemputan dari bandara ke penginapan." },
    { id: "a2", group: "Keluarga Risyqaa (luar kota)", from: "", date: "2026-08-17", time: "", transport: "", count: "", note: "Datang H-1, sebelum gladi." },
  ],
  lodging: [
    { id: "l1", name: "", address: "", phone: "", rooms: "", forGroup: "Keluarga Falah (Pare, Kediri)", mapUrl: "", note: "Cari yang dekat venue di Mempawah. Check-in 16 Agustus." },
  ],
  routes: [
    { id: "rt1", from: "Bandara Supadio, Pontianak", to: "Penginapan di Mempawah", mode: "Mobil / rental", duration: "± 2 jam", mapUrl: "", note: "Sediakan mobil jemputan untuk rombongan Kediri." },
    { id: "rt2", from: "Penginapan di Mempawah", to: "Mempawah Convention Center", mode: "Mobil", duration: "–", mapUrl: "", note: "Berangkat pagi hari-H, sebelum akad jam 08:00." },
  ],
  vendors: [
    { id: "v1", category: "Venue (MCC)", name: "", phone: "" },
    { id: "v2", category: "Catering", name: "", phone: "" },
    { id: "v3", category: "Dekorasi", name: "", phone: "" },
    { id: "v4", category: "Fotografer/Videografer", name: "", phone: "" },
    { id: "v5", category: "MUA", name: "", phone: "" },
    { id: "v6", category: "Busana", name: "", phone: "" },
    { id: "v7", category: "Sound/MC/Hiburan", name: "", phone: "" },
    { id: "v8", category: "WO / Koordinator", name: "", phone: "" },
  ],
  budgetItems: [
    { id: "b1", pos: "Sewa Venue", low: 5000000, high: 10000000, note: "Konfirmasi langsung ke pengelola MCC" },
    { id: "b2", pos: "Catering (700 tamu)", low: 60000000, high: 75000000, note: "Pos terbesar, ± Rp85–105rb/porsi" },
    { id: "b3", pos: "Dekorasi", low: 20000000, high: 25000000, note: "Fokus pelaminan & panggung utama" },
    { id: "b4", pos: "Dokumentasi", low: 8000000, high: 12000000, note: "Foto + video" },
    { id: "b5", pos: "Busana & MUA", low: 10000000, high: 15000000, note: "" },
    { id: "b6", pos: "Sound, MC, Hiburan", low: 8000000, high: 12000000, note: "" },
    { id: "b7", pos: "Undangan", low: 2000000, high: 3000000, note: "Prioritaskan digital" },
    { id: "b8", pos: "Akomodasi & transport keluarga", low: 5000000, high: 8000000, note: "Penginapan & jemputan dari bandara" },
    { id: "b10", pos: "Administrasi nikah (KUA, bimwin, penghulu)", low: 1000000, high: 2000000, note: "Termasuk akad di luar KUA & suntik TT" },
    { id: "b11", pos: "Cincin kawin", low: 5000000, high: 10000000, note: "Terpisah dari mahar" },
    { id: "b12", pos: "Kue pengantin", low: 1000000, high: 3000000, note: "" },
    { id: "b13", pos: "Souvenir tamu (± 700)", low: 3500000, high: 7000000, note: "± Rp5–10rb per buah" },
    { id: "b14", pos: "Genset/backup listrik", low: 2000000, high: 4000000, note: "Antisipasi mati listrik untuk 700 tamu" },
    { id: "b15", pos: "Parkir, keamanan & P3K", low: 2000000, high: 4000000, note: "Petugas parkir, security, medis standby" },
    { id: "b16", pos: "Busana keluarga & seragam panitia", low: 5000000, high: 10000000, note: "Orang tua kedua pihak + among tamu" },
    { id: "b17", pos: "Perawatan pengantin", low: 1500000, high: 3000000, note: "Facial/spa sebelum hari-H" },
    { id: "b18", pos: "Qori & pembaca doa", low: 500000, high: 1500000, note: "" },
    { id: "b19", pos: "Uang tip kru vendor", low: 1000000, high: 2000000, note: "Sering lupa dianggarkan" },
    { id: "b9", pos: "Dana Cadangan", low: 10000000, high: 15000000, note: "Wajib disisihkan" },
  ],
  expenses: [
    { id: "e1", item: "DP sewa venue", category: "Sewa Venue", amount: 0, date: "", paid: false, note: "" },
  ],
};
