import type { ProgressData } from "./types";

// Reset untuk pernikahan Saiful & Nufus — isi ulang checklist/rundown/dsb.
// sesuai kebutuhan lewat mode "Edit" di /persiapan (tersimpan otomatis).
export const DEFAULT_DATA: ProgressData = {
  settings: {
    nameFirst: "Saiful Amri Tanjung",
    nameSecond: "Nufus Nurcholisoh",
    weddingDate: "2026-11-01",
    ceremonyTime: "08:00",
    venue: "Rumah Mempelai Wanita, Pandeglang",
    venueMapUrl: "",
    totalBudget: 0,
  },
  tasks: [
    { id: "t01", text: "Konfirmasi tanggal & lokasi ke pihak keluarga mempelai wanita", pic: "Kedua mempelai", date: "", done: false },
    { id: "t02", text: "Mulai administrasi nikah di KUA/kelurahan domisili", pic: "", date: "", done: false },
    { id: "t03", text: "Survei & DP catering", pic: "", date: "", done: false },
    { id: "t04", text: "Survei & DP dekorasi", pic: "", date: "", done: false },
    { id: "t05", text: "Booking fotografer & videografer", pic: "", date: "", done: false },
    { id: "t06", text: "Booking MUA & busana pengantin", pic: "", date: "", done: false },
    { id: "t07", text: "Booking sound system, MC, hiburan", pic: "", date: "", done: false },
    { id: "t08", text: "Finalisasi rundown acara", pic: "", date: "", done: false },
    { id: "t09", text: "Desain undangan digital (WA/e-invitation)", pic: "", date: "", done: false },
    { id: "t10", text: "Finalisasi daftar tamu", pic: "", date: "", done: false },
    { id: "t11", text: "Mulai sebar undangan", pic: "", date: "", done: false },
    { id: "t12", text: "Fitting busana pengantin", pic: "", date: "", done: false },
    { id: "t13", text: "DP mahar & seserahan", pic: "", date: "", done: false },
    { id: "t14", text: "Rapat teknis dengan vendor (rundown, denah, jam kerja)", pic: "", date: "", done: false },
    { id: "t15", text: "Selesaikan seluruh dokumen administrasi nikah", pic: "Kedua mempelai", date: "", done: false },
    { id: "t16", text: "Ikuti Bimbingan Perkawinan (bimwin) & urus sertifikatnya", pic: "Kedua mempelai", date: "", done: false },
    { id: "t17", text: "Konfirmasi penghulu, saksi & wali nikah", pic: "", date: "", done: false },
    { id: "t18", text: "Pesan cincin kawin", pic: "", date: "", done: false },
    { id: "t19", text: "Pesan souvenir tamu", pic: "", date: "", done: false },
    { id: "t20", text: "Pantau RSVP & konfirmasi jumlah tamu final ke catering", pic: "", date: "", done: false },
    { id: "t21", text: "H-1: Gladi & setup, cek sound & listrik", pic: "", date: "", done: false },
    { id: "t22", text: "Hari-H: Nikmati acara!", pic: "Kedua mempelai", date: "2026-11-01", done: false },
  ],
  rundown: [
    { id: "r1", time: "06:00", activity: "Persiapan & make-up pengantin", note: "MUA tiba di lokasi", pic: "MUA" },
    { id: "r2", time: "08:00", activity: "Akad Nikah", note: "Penghulu & saksi hadir", pic: "Keluarga inti" },
    { id: "r3", time: "09:00", activity: "Sesi foto keluarga", note: "Setelah akad", pic: "Fotografer" },
    { id: "r4", time: "12:00", activity: "Resepsi & ramah tamah", note: "", pic: "MC" },
    { id: "r5", time: "17:00", activity: "Penutupan", note: "", pic: "WO" },
  ],
  arrivals: [],
  lodging: [],
  routes: [],
  vendors: [
    { id: "v1", category: "Venue", name: "", phone: "" },
    { id: "v2", category: "Catering", name: "", phone: "" },
    { id: "v3", category: "Dekorasi", name: "", phone: "" },
    { id: "v4", category: "Fotografer/Videografer", name: "", phone: "" },
    { id: "v5", category: "MUA", name: "", phone: "" },
    { id: "v6", category: "Busana", name: "", phone: "" },
    { id: "v7", category: "Sound/MC/Hiburan", name: "", phone: "" },
    { id: "v8", category: "WO / Koordinator", name: "", phone: "" },
  ],
  budgetItems: [],
  expenses: [],
  familyItinerary: [],
};
